### PR TITLE
fix issue with feedback 

### LINKED ISSUE #409: Feedback form not working properly
When you insert feedback in the feedback field it doesn't send the proper data into knowledgebase. It just tracks the correct FAQ without the actual content of the feedback. Also the timestamp is wrong. 

Issue: http://recordit.co/Uez2XgSXgt

Timestamp showing 9:23pm when it actually was 11:23pm.

### PR DESCRIPTION
**Pull request by jalbertsr**
Close #409 <br/><br/><br/><url>LiveURL: https://smartfaq-409-feedback-bug.surge.sh</url>

### CODE REVIEW

File: src/StaticFAQ/ArticleFeedback/ScreenInput.js [hunk 1]
```diff
@@ -97,7 +97,11 @@ class ScreenInput extends React.Component<Props, State> {
             <Text>What problem were you trying to solve?</Text>
           </div>
           <div className="inputArea">
-            <textarea data-gramm_editor="false" required />
+            <textarea
+              data-gramm_editor="false"
+              onChange={this.handleChange}
```
Comment (jaroslav-kubicek) [inline src/StaticFAQ/ArticleFeedback/ScreenInput.js]: no value?

Comment (jalbertsr) [reply src/StaticFAQ/ArticleFeedback/ScreenInput.js]: 🤦‍♂️ thx, fixed
