### PR TITLE
Scenario "User can't log in SmartFAQ with bad credentials" implemented

### LINKED ISSUE #246: Implement scenario "User can't log in with bad credentials"
```
Given user clicks on "I have existing booking"
When he choose "I want to use my Kiwi.com account"
And fill in the form with **incorrect** credentials
Then user should see "The username or password you've entered is invalid." error
```

### PR DESCRIPTION
**Pull request by edgarordonez**
Close #246

- This PR are using code from this other PR https://github.com/kiwicom/smart-faq/pull/279. So, I guess that we need to merge this before.

- Scenario "User can't log in SmartFAQ with bad credentials" has been implemented.<br/><br/><br/><url>LiveURL: https://smartfaq-246-cypress-user-can-not-log-bad-credentials.surge.sh</url>

### CODE REVIEW

File: cypress/integration/User_can_log_into_SmartFAQ.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+    cy.visit('/');
+    cy.get('[data-cy=btn-existent-booking]').click();
+    cy.get('[data-cy=link-kiwi-login]').click();
+  });
+
+  it(`The user should be able to log into SmartFAQ with the correct credentials.`, () => {
+    cy.get('[data-cy=input-email]').type(Cypress.env('TEST_USER_EMAIL'));
+    cy.get('[data-cy=input-password]').type(Cypress.env('TEST_USER_PASSWORD'));
+    cy.get('[data-cy=btn-sign-in]').click();
+    cy.wait(1000);
```
Comment (dinodsaurus) [inline cypress/integration/User_can_log_into_SmartFAQ.js]: I dont think this is a good idea, because it could happen that it fails randomly.
But then again Im not sure if we should mock login functionality..
What do you think @git-toni @jaroslav-kubicek

Comment (edgarordonez) [reply cypress/integration/User_can_log_into_SmartFAQ.js]: Yes, agree!

But... I don't know how to do without a mock. 
We need to find a better approach to do this.

Ideas? @git-toni @jaroslav-kubicek 

Thanks, @dinodsaurus !

File: cypress/integration/UserCanLogIntoSmartFAQ.js [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+  Cypress,
+  cy
+*/
+
+describe('User can log into SmartFAQ', () => {
+  beforeEach(() => {
+    const mocks = {
+      'https://auth.skypicker.com/v1/user.login': {
+        token:
+          'WyJ4OExkeng0NzU2TUV0b0FfQkI4MWFXIiwiZ0NwUVVlWjRqVkJ0Y1NSbm5YMmVRLmViRlFQUmYxRTY2cTMwSGZiaDJnMnhmMzN4R3RldDYiLDg4MDEzOTEwMl0.SYeh92_bED-iGshCHdgQCL_ryRo',
```
Comment (dinodsaurus) [inline cypress/integration/UserCanLogIntoSmartFAQ.js]: You can move this to `cypress/fixtures` folder.

File: cypress/integration/UserCanLogIntoSmartFAQ.js [hunk 3]
```diff
@@ -6,16 +6,19 @@
 
 describe('User can log into SmartFAQ', () => {
   beforeEach(() => {
-    cy.visit('/');
-    cy.get('[data-cy=btn-existent-booking]').click();
-    cy.get('[data-cy=link-kiwi-login]').click();
+    cy
+      .fixture('UserCanLogIntoSmartFAQ_Mock.json')
```
Comment (dinodsaurus) [inline cypress/integration/UserCanLogIntoSmartFAQ.js]: Nice!
