### PR TITLE
Extend query params redirect integration test

### LINKED ISSUE #586: Extend cypress test
Extend cypress test `QueryParamsRedirects.js` that verifies the link to a specific article to test also clicking on back button to cover the bug reported here: #568

### PR DESCRIPTION
**Pull request by vborszeki**
closes #586 <br/><br/><br/><url>LiveURL: https://smartfaq-extend-query-params-redirects-test.surge.sh</url>

### CODE REVIEW

File: cypress/integration/QueryParamsRedirects.js [hunk 1]
```diff
@@ -2,28 +2,42 @@
...
 
-  it(`Article title should be corect`, () => {
+  it(`should display correct article title`, () => {
     cy
       .get('.faq-article-detail')
       .find('h1')
       .contains('Cabin baggage');
   });
+
+  it('should display the root FAQ categories after clicking home breadcrumb', () => {
```
Comment (kantord) [inline cypress/integration/QueryParamsRedirects.js]: > should display the root FAQ categories after clicking home breadcrumb

It should be `should display parent FAQ categories after clicking home breadcrumb` as tests for all parents, not only root.
