### PR TITLE
157 logout stale session

### LINKED ISSUE #157: Refactor our custom QueryRenderer
Repro steps:
- User is logged in, but his session is stale
- GraphQL query return 403 Forbidden

Expected
- 403 is recognized, `onLogout` callback is called, so stale user session is safely destroyed

Actual: just blank error is shown: see the screen

screen shot 2018-05-10 at 16 17 17

### PR DESCRIPTION
**Pull request by git-toni**
Closes #157 

Rather simple approach based on throwing error upon non-200 response instead of refactoring our custom `QueryRenderer`.

Other screens might have to replicate this feature so another option is to move the `onLogout` + redirect logic to an external helper.

### CODE REVIEW

File: src/SingleBookingPage/index.js [hunk 1]
```diff
@@ -30,6 +36,10 @@ const query = graphql`
 class SingleBookingPage extends React.Component<Props> {
   renderBooking = (renderState: RenderState) => {
     if (renderState.error) {
+      if (renderState.error.message === ERROR_FORBIDDEN) {
+        this.props.onLogout();
```
Comment (jaroslav-kubicek) [inline src/SingleBookingPage/index.js]: doesn't `onLogout` return promise? it should be awaited in such case

File: src/relay/netorkErrors.js [hunk 2]
```diff
@@ -0,0 +1,3 @@
+// @flow
```
Comment (jaroslav-kubicek) [inline src/relay/netorkErrors.js]: typo in filename

Comment (jaroslav-kubicek) [reply src/relay/netorkErrors.js]: there is no necessity to have it defined in separate file, it's overkill ==> relay/environment.js

File: src/relay/environment.js [hunk 3]
```diff
@@ -41,6 +42,12 @@ const buildFetchQuery = (
       }),
     });
     const json = await response.json();
+    if (json.errors && json.errors.length > 0) {
+      const errorMsg = json.errors.some(e => e._proxy.statusCode === 403)
+        ? ERROR_FORBIDDEN
+        : '';
+      throw new Error(errorMsg);
```
Comment (jaroslav-kubicek) [inline src/relay/environment.js]: - We should allow partial errors
- throwing error with empty message doesn't make much sense

File: src/SingleBookingPage/index.js (hunk 1 above)
Comment (jaroslav-kubicek) [reply src/SingleBookingPage/index.js]: also, probably could be moved to custom QueryRenderer

**Comment by git-toni** [comment]
cc @jaroslav-kubicek

File: src/context/Language.js [hunk 4]
```diff
@@ -5,3 +5,16 @@ import * as React from 'react';
...
 
 export const LanguageContext = React.createContext(defaultLanguage);
+
+export const withDefaultLanguage = <Props>(
+  Component: React.ComponentType<{ defaultLanguage: string } & Props>,
+) =>
+  function withLanguageHOC(props: Props) {
+    return (
+      <LanguageContext.Consumer>
+        {(defaultLanguage: string) => (
```
Comment (jaroslav-kubicek) [inline src/context/Language.js]: `defaultLanguage` is rather unfortunate name for language prop

File: src/relay/QueryRenderer.js [hunk 5]
```diff
@@ -18,25 +20,41 @@ type Props<RenderProps> = {|
...
+};
+type RenderState<RenderProps> = {
+  props: ?RenderProps,
+  error: ?Error,
+};
+class QueryRenderer extends React.Component<ContextTypes & Props<RenderProps>> {
+  renderContainer = (renderState: RenderState<RenderProps>) => {
+    if (renderState.error) {
+      if (renderState.error.message === ERROR_FORBIDDEN) {
+        this.props.onLogout().then(() => {
```
Comment (jaroslav-kubicek) [inline src/relay/QueryRenderer.js]: should use async/await instead

File: src/ContentPage/index.js [hunk 6]
```diff
@@ -84,12 +91,21 @@ const FAQRoutes = (
     </Switch>
   </MemoryRouter>
 );
-const ContentPage = () => {
+
+type Props = {
+  history: RouterHistory,
+};
+const ContentPage = (props: Props) => {
+  const returnToLogin = () =>
```
Comment (jaroslav-kubicek) [inline src/ContentPage/index.js]: this should be moved down to `QueryRenderer` as well, no need to pass it down as prop

File: src/context/Language.js (hunk 4 above)
Comment (git-toni) [reply src/context/Language.js]: :smile: I don't find it that crazy offtopic, but you've got a point. What about `language`? :book:

File: src/relay/QueryRenderer.js (hunk 5 above)
Comment (git-toni) [reply src/relay/QueryRenderer.js]: How do we do that before they land [async rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) in React?

File: src/ContentPage/index.js (hunk 6 above)
Comment (git-toni) [reply src/ContentPage/index.js]: The problem I faced here and why I ended up with this rather ugly solution is that QueryRenderer is instantiated by many different components, and some of the components are not rendered under the "main" MemoryRouter. But I am only interested in the returnToLogin that pushes history to the "main" router(the parent of ContentPage, otherwise I would only redirect to login half of the page, ie. a sub-router like the one of BookingRoutes in Line 48 here. Hence I cannot decorate QueryRenderer with withRouter cause that would not be linked to the desired main MemoryRouter instance.

All of this will be thankfully obsolete with your new proposal for Routing. So I am totally fine having you merge the new routing system first, and then rebasing this PR, however painful. slightly_smiling_face

File: src/relay/QueryRenderer.js (hunk 5 above)
Comment (jaroslav-kubicek) [reply src/relay/QueryRenderer.js]: good point 🤔 

maybe 
```
(async () => { 
  await something(); 
})().catch(console.error)
```

File: src/ContentPage/index.js (hunk 6 above)
Comment (jaroslav-kubicek) [reply src/ContentPage/index.js]: ok, le's merge it and let's suffer in my PR
