### PR TITLE
Fix header on frontend

### LINKED ISSUE #253: Fix header on frontend
screen shot 2018-05-28 at 14 49 51

Header is broken because of class name collision with frontend css - `.Header` classname must be renamed to something different.

### PR DESCRIPTION
**Pull request by edgarordonez**
Close #253 

- Changed CSS property to solve the header broken. (I think that change the name of the class isn't needed).<br/><br/><br/><url>LiveURL: https://smartfaq-253-fix-header-frontend.surge.sh</url>

### CODE REVIEW

File: src/common/layout/Header.js [hunk 1]
```diff
@@ -47,6 +47,7 @@ const loggedInStyle = css`
   .loggedIn {
     display: flex;
     justify-content: space-between;
+    flex: 1;
```
Comment (jaroslav-kubicek) [inline src/common/layout/Header.js]: I would rather rename the class - they still can decide to change styles for `Header` anytime, which could affect us.
