### PR TITLE
Show warning for reaching article comment limit

### LINKED ISSUE #740: Improve error handling of feedback form
1. if REST API returns `you exceed limit for comments count per day`, show user that the daily limit was reached
2. track by analytics that the limit on commenting was reached
~~3. GraphQL mutation `addFAQArticleComment` should return such "user error" as a regular field in data, not an exception in `{ errors: [] }` field~~

edit: the last point moved to #758

### PR DESCRIPTION
**Pull request by vborszeki**
closes #740<br/><br/><br/><url>LiveURL: https://smartfaq-article-feedback-error.surge.sh</url>

### CODE REVIEW

File: src/mutations/CreateCommentMutation.js [hunk 1]
```diff
@@ -34,10 +36,15 @@ export default (
     onCompleted: (response, errors) => {
       if (!errors) {
         callback();
-      } else {
-        errorCallback();
       }
+
+      if (errors[0].extensions.proxy.statusCode === '429') {
```
Comment (jaroslav-kubicek) [inline src/mutations/CreateCommentMutation.js]: this is a quite dangerous way how to access error code. there is no guarantee GraphQL errors have these fields every time.

File: src/StaticFAQ/ArticleFeedback/ScreenCommentLimit.js [hunk 2]
```diff
@@ -0,0 +1,49 @@
+// @flow
+
```
Comment (jaroslav-kubicek) [inline src/StaticFAQ/ArticleFeedback/ScreenCommentLimit.js]: this component is suspiciously similar to ScreenError, doesn't it make sense to have just one?
