### PR TITLE
fix(booking-types): rename booking-types - 267

### LINKED ISSUE #267: We have a component named `<Return />`
In `bookingTypes` we have
-  Return
-  Multicity
- Oneway

`<Return />` is a bit confusing, so it should be renamed to something like `<ReturnTrip />`. For consistency's sake, all the other component names in `bookingTypes` should be suffixed with Trip as well (`MultiCityTrip` and `OneWayTrip`)

### PR DESCRIPTION
**Pull request by jalbertsr**
close #267<br/><br/><br/><url>LiveURL: https://smartfaq-267-rename-files.surge.sh</url>

### CODE REVIEW

File: src/SingleBookingPage/bookingTypes/MulticityOverlayTrip.js [hunk 1]
```diff
@@ -3,7 +3,7 @@
 import * as React from 'react';
 import { createFragmentContainer, graphql } from 'react-relay';
 
-import Multicity from './Multicity';
+import Multicity from './MulticityTrip';
```
Comment (vborszeki) [inline src/SingleBookingPage/bookingTypes/MulticityOverlayTrip.js]: I think you forgot to rename the import itself and it's usages below 🙂

Comment (jalbertsr) [reply src/SingleBookingPage/bookingTypes/MulticityOverlayTrip.js]: good catch, fixed
